
-- ************************* SqlDBM: PostgreSQL *************************
-- ******* Generated by SqlDBM: NESBox, v8 by 594mantou@gmail.com *******



-- ************************************** users

CREATE TABLE users
(
 "id"         integer NOT NULL GENERATED ALWAYS AS IDENTITY,
 username   varchar(20) NOT NULL,
 password   varchar(20) NOT NULL,
 nickname   varchar(20) NOT NULL,
 settings   json NULL,
 deleted_at timestamp NULL,
 created_at timestamp NOT NULL,
 updated_at timestamp NOT NULL,
 status     varchar(20) NOT NULL,
 CONSTRAINT PK_6 PRIMARY KEY ( "id" ),
 CONSTRAINT Index_7 UNIQUE ( username )
);


CREATE TABLE games
(
 "id"          integer NOT NULL GENERATED ALWAYS AS IDENTITY,
 name        varchar(20) NOT NULL,
 description text NOT NULL,
 preview     character(50) NOT NULL,
 deleted_at  timestamp NULL,
 created_at  timestamp NOT NULL,
 updated_at  timestamp NOT NULL,
 rom         character(50) NOT NULL,
 CONSTRAINT PK_10 PRIMARY KEY ( "id" ),
 CONSTRAINT Index_13 UNIQUE ( name )
);


CREATE TABLE rooms
(
 "id"         integer NOT NULL GENERATED ALWAYS AS IDENTITY,
 game_id    integer NOT NULL,
 "private"    boolean NOT NULL,
 created_at timestamp NOT NULL,
 updated_at timestamp NOT NULL,
 deleted_at timestamp NULL,
 CONSTRAINT PK_54 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_84 FOREIGN KEY ( game_id ) REFERENCES games ( "id" )
);

CREATE INDEX FK_86 ON rooms
(
 game_id
);



CREATE TABLE comments
(
 user_id    integer NOT NULL,
 game_id    integer NOT NULL,
 body       text NOT NULL,
 "like"       boolean NOT NULL,
 deleted_at timestamp NULL,
 created_at timestamp NOT NULL,
 updated_at timestamp NOT NULL,
 CONSTRAINT PK_17 PRIMARY KEY ( user_id, game_id ),
 CONSTRAINT FK_27 FOREIGN KEY ( game_id ) REFERENCES games ( "id" ),
 CONSTRAINT FK_30 FOREIGN KEY ( user_id ) REFERENCES users ( "id" )
);

CREATE INDEX FK_29 ON comments
(
 game_id
);

CREATE INDEX FK_32 ON comments
(
 user_id
);

CREATE TABLE favorites
(
 user_id    integer NOT NULL,
 game_id    integer NOT NULL,
 created_at timestamp NOT NULL,
 CONSTRAINT PK_116 PRIMARY KEY ( user_id, game_id ),
 CONSTRAINT FK_113 FOREIGN KEY ( game_id ) REFERENCES games ( "id" ),
 CONSTRAINT FK_117 FOREIGN KEY ( user_id ) REFERENCES users ( "id" )
);

CREATE INDEX FK_115 ON favorites
(
 game_id
);

CREATE INDEX FK_119 ON favorites
(
 user_id
);


CREATE TABLE friends
(
 user_id    integer NOT NULL,
 target_id  integer NOT NULL,
 created_at timestamp NOT NULL,
 status     varchar(20) NOT NULL,
 CONSTRAINT PK_42 PRIMARY KEY ( user_id, target_id ),
 CONSTRAINT FK_39 FOREIGN KEY ( user_id ) REFERENCES users ( "id" ),
 CONSTRAINT FK_43 FOREIGN KEY ( target_id ) REFERENCES users ( "id" )
);

CREATE INDEX FK_41 ON friends
(
 user_id
);

CREATE INDEX FK_45 ON friends
(
 target_id
);





CREATE TABLE invites
(
 "id"         integer NOT NULL GENERATED ALWAYS AS IDENTITY,
 room_id    integer NOT NULL,
 target_id  integer NOT NULL,
 user_id    integer NOT NULL,
 created_at timestamp NOT NULL,
 deleted_at timestamp NULL,
 updated_at timestamp NOT NULL,
 CONSTRAINT PK_127 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_131 FOREIGN KEY ( user_id ) REFERENCES users ( "id" ),
 CONSTRAINT FK_134 FOREIGN KEY ( target_id ) REFERENCES users ( "id" ),
 CONSTRAINT FK_170 FOREIGN KEY ( room_id ) REFERENCES rooms ( "id" )
);

CREATE INDEX FK_133 ON invites
(
 user_id
);

CREATE INDEX FK_136 ON invites
(
 target_id
);

CREATE INDEX FK_172 ON invites
(
 room_id
);


CREATE TABLE messages
(
 "id"         integer NOT NULL GENERATED ALWAYS AS IDENTITY,
 body       text NOT NULL,
 target_id  integer NOT NULL,
 user_id    integer NOT NULL,
 deleted_at timestamp NULL,
 created_at timestamp NOT NULL,
 updated_at timestamp NOT NULL,
 CONSTRAINT PK_104 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_106 FOREIGN KEY ( user_id ) REFERENCES users ( "id" ),
 CONSTRAINT FK_109 FOREIGN KEY ( target_id ) REFERENCES users ( "id" )
);

CREATE INDEX FK_108 ON messages
(
 user_id
);

CREATE INDEX FK_111 ON messages
(
 target_id
);


CREATE TABLE playing
(
 user_id    integer NOT NULL,
 room_id    integer NOT NULL,
 created_at timestamp NOT NULL,
 CONSTRAINT PK_142 PRIMARY KEY ( user_id, room_id ),
 CONSTRAINT FK_143 FOREIGN KEY ( user_id ) REFERENCES users ( "id" ),
 CONSTRAINT FK_175 FOREIGN KEY ( room_id ) REFERENCES rooms ( "id" )
);

CREATE INDEX FK_145 ON playing
(
 user_id
);

CREATE INDEX FK_177 ON playing
(
 room_id
);


